# Generated by Django 5.2.7 on 2025-10-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, unique=True, verbose_name="用户名"),
                ),
                (
                    "user_id",
                    models.CharField(max_length=100, unique=True, verbose_name="用户ID"),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, verbose_name="显示名称"),
                ),
                (
                    "profile_image_url",
                    models.URLField(blank=True, verbose_name="头像URL"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用监控")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后检查时间"),
                ),
            ],
            options={
                "verbose_name": "监控用户",
                "verbose_name_plural": "监控用户",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "tweets_fetched",
                    models.IntegerField(default=0, verbose_name="获取推文数"),
                ),
                (
                    "replies_fetched",
                    models.IntegerField(default=0, verbose_name="获取回复数"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="twitter_monitor.monitoreduser",
                        verbose_name="监控用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控日志",
                "verbose_name_plural": "监控日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tweet_id",
                    models.CharField(max_length=100, unique=True, verbose_name="推文ID"),
                ),
                (
                    "tweet_type",
                    models.CharField(
                        choices=[
                            ("tweet", "原创推文"),
                            ("retweet", "转发"),
                            ("quote", "引用转发"),
                        ],
                        default="tweet",
                        max_length=20,
                        verbose_name="推文类型",
                    ),
                ),
                ("text", models.TextField(verbose_name="推文内容")),
                ("created_at", models.DateTimeField(verbose_name="发布时间")),
                ("retweet_count", models.IntegerField(default=0, verbose_name="转发数")),
                ("reply_count", models.IntegerField(default=0, verbose_name="回复数")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("quote_count", models.IntegerField(default=0, verbose_name="引用数")),
                (
                    "referenced_tweet_id",
                    models.CharField(blank=True, max_length=100, verbose_name="引用推文ID"),
                ),
                (
                    "retweeted_tweet_id",
                    models.CharField(blank=True, max_length=100, verbose_name="转发推文ID"),
                ),
                ("has_media", models.BooleanField(default=False, verbose_name="包含媒体")),
                (
                    "media_urls",
                    models.JSONField(blank=True, default=list, verbose_name="媒体URL列表"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="抓取时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        to="twitter_monitor.monitoreduser",
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "推文",
                "verbose_name_plural": "推文",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reply_id",
                    models.CharField(max_length=100, unique=True, verbose_name="回复ID"),
                ),
                ("text", models.TextField(verbose_name="回复内容")),
                ("created_at", models.DateTimeField(verbose_name="回复时间")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("reply_count", models.IntegerField(default=0, verbose_name="回复数")),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="抓取时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="twitter_monitor.monitoreduser",
                        verbose_name="回复者",
                    ),
                ),
                (
                    "tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="twitter_monitor.tweet",
                        verbose_name="原推文",
                    ),
                ),
            ],
            options={
                "verbose_name": "回复",
                "verbose_name_plural": "回复",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(
                fields=["-created_at"], name="twitter_mon_created_08d3dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(
                fields=["tweet_id"], name="twitter_mon_tweet_i_4945c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(
                fields=["author", "-created_at"], name="twitter_mon_author__9b0a87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(
                fields=["tweet", "-created_at"], name="twitter_mon_tweet_i_8239ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reply",
            index=models.Index(
                fields=["author", "-created_at"], name="twitter_mon_author__8c763a_idx"
            ),
        ),
    ]
